import React, { useEffect, useState } from 'react';
import Layout from '../components/Layout';
import { Sparkles, AlertCircle, Leaf, Zap, BarChart2 } from 'lucide-react';
import { getAnalysisApi } from '../api/analysisApi';

export default function AiInsights() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function loadData() {
      try {
        const response = await getAnalysisApi();
        setData(response.data);
      } catch (err) {
        setError('Failed to load AI Insights.');
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, []);

  return (
    <Layout activeMenu="AI Insights">
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
          <Sparkles className="text-emerald-500" />
          AI Strategic Insights
        </h2>
        <p className="text-gray-500 text-sm mt-1">Generated by CarbonTrace AI Engine</p>
      </div>

      {loading ? (
        <div className="flex justify-center items-center h-64">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-emerald-600"></div>
        </div>
      ) : error ? (
        <div className="bg-red-50 border border-red-200 text-red-600 p-4 rounded-xl flex items-center gap-3">
          <AlertCircle size={20} />
          <p>{error}</p>
        </div>
      ) : data ? (
        <div className="space-y-6">
          <div className="bg-white rounded-2xl border border-gray-200 p-6 shadow-sm border-t-4 border-t-emerald-400">
            <h3 className="font-bold text-lg text-gray-900 mb-4 flex items-center gap-2">
              <Sparkles size={20} className="text-emerald-500" /> Executive AI Summary
            </h3>
            <p className="text-gray-700 leading-relaxed text-sm">
              {data.aiSummaryParagraph}
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-white rounded-2xl border border-gray-200 p-6 shadow-sm">
              <h3 className="font-bold text-lg text-gray-900 mb-4 flex items-center gap-2">
                <BarChart2 size={20} className="text-emerald-500" /> Top Emission Sources
              </h3>
              <div className="space-y-4">
                {data.topEmissionSources?.map((source, index) => (
                  <div key={index} className="flex flex-col gap-1">
                    <div className="flex justify-between text-sm">
                      <span className="font-semibold text-gray-700">{source.source}</span>
                      <span className="font-bold text-gray-900">{source.emissions.toLocaleString()} {source.unit}</span>
                    </div>
                    <div className="w-full bg-gray-100 rounded-full h-2">
                      <div 
                        className="bg-emerald-500 h-2 rounded-full" 
                        style={{ width: `${source.percentage}%` }}
                      ></div>
                    </div>
                    <span className="text-xs text-gray-500">{source.percentage}% of total</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-white rounded-2xl border border-gray-200 p-6 shadow-sm">
              <h3 className="font-bold text-lg text-gray-900 mb-4 flex items-center gap-2">
                <Leaf size={20} className="text-emerald-500" /> Overview
              </h3>
              <div className="grid grid-cols-2 gap-4">
                <div className="bg-gray-50 p-4 rounded-xl border border-gray-100">
                  <p className="text-xs text-gray-500 uppercase font-semibold mb-1">Total Carbon Footprint</p>
                  <p className="text-2xl font-bold text-gray-900">{data.totalCarbonFootprint?.toLocaleString()}</p>
                  <p className="text-xs text-emerald-600 font-medium">{data.unit}</p>
                </div>
                <div className="bg-gray-50 p-4 rounded-xl border border-gray-100">
                  <p className="text-xs text-gray-500 uppercase font-semibold mb-1">Calculation Engine</p>
                  <p className="text-sm font-bold text-gray-900 mt-2">{data.calculationEngine}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="bg-gray-50 border border-gray-200 text-gray-600 p-4 rounded-xl">
          No insights available. Please complete onboarding.
        </div>
      )}
    </Layout>
  );
}
